-- Expand-only governance evidence store.  No model or source is activated by
-- this migration; all new records start in a non-production state.

CREATE TABLE model_releases (
    id BIGINT NOT NULL AUTO_INCREMENT,
    release_id VARCHAR(128) NOT NULL,
    model_name VARCHAR(128) NOT NULL,
    model_version VARCHAR(128) NOT NULL,
    weight_sha256 VARCHAR(64) NOT NULL,
    artifact_signature VARCHAR(4096) NOT NULL,
    signature_algorithm VARCHAR(64) NOT NULL,
    prompt_version VARCHAR(128) NOT NULL,
    embedding_version VARCHAR(128) NOT NULL,
    knowledge_index_version VARCHAR(128) NOT NULL,
    scope VARCHAR(1024) NOT NULL,
    gpu_baseline_json LONGTEXT NOT NULL,
    release_status VARCHAR(32) NOT NULL,
    rollback_target_release_id VARCHAR(128) NULL,
    created_by VARCHAR(128) NOT NULL,
    approved_by VARCHAR(128) NULL,
    approved_at TIMESTAMP(6) NULL,
    frozen_at TIMESTAMP(6) NULL,
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uk_model_releases_release_id (release_id),
    KEY idx_model_releases_status (release_status),
    KEY idx_model_releases_model_version (model_name, model_version)
);

CREATE TABLE clinical_evaluation_runs (
    id BIGINT NOT NULL AUTO_INCREMENT,
    run_id VARCHAR(128) NOT NULL,
    release_id VARCHAR(128) NOT NULL,
    dataset_version VARCHAR(128) NOT NULL,
    dataset_sha256 VARCHAR(64) NOT NULL,
    de_identification_method VARCHAR(512) NOT NULL,
    sample_count INT NOT NULL,
    sensitivity DOUBLE NOT NULL,
    specificity DOUBLE NOT NULL,
    false_negative_count INT NOT NULL,
    incorrect_routing_count INT NOT NULL,
    abstention_rate DOUBLE NOT NULL,
    thresholds_json LONGTEXT NOT NULL,
    evaluation_status VARCHAR(32) NOT NULL,
    evidence_uri VARCHAR(2048) NOT NULL,
    evaluated_by VARCHAR(128) NOT NULL,
    reviewed_by VARCHAR(128) NULL,
    reviewed_at TIMESTAMP(6) NULL,
    created_at TIMESTAMP(6) NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uk_clinical_evaluation_run_id (run_id),
    KEY idx_evaluation_release_status (release_id, evaluation_status),
    KEY idx_evaluation_created_at (created_at)
);

CREATE TABLE knowledge_source_register (
    id BIGINT NOT NULL AUTO_INCREMENT,
    source_id VARCHAR(128) NOT NULL,
    doc_id VARCHAR(128) NOT NULL,
    publisher VARCHAR(256) NOT NULL,
    title VARCHAR(512) NOT NULL,
    url VARCHAR(2048) NOT NULL,
    domestic_official BOOLEAN NOT NULL DEFAULT FALSE,
    publication_date VARCHAR(10) NOT NULL,
    source_version VARCHAR(256) NOT NULL,
    checksum VARCHAR(64) NOT NULL,
    applicable_scope VARCHAR(1024) NOT NULL,
    review_status VARCHAR(32) NOT NULL,
    reviewer VARCHAR(128) NULL,
    reviewed_at TIMESTAMP(6) NULL,
    expires_at TIMESTAMP(6) NULL,
    created_at TIMESTAMP(6) NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uk_knowledge_source_register_source_id (source_id),
    KEY idx_source_register_status (review_status),
    KEY idx_source_register_doc (doc_id)
);

CREATE TABLE governance_changes (
    id BIGINT NOT NULL AUTO_INCREMENT,
    change_id VARCHAR(128) NOT NULL,
    target_type VARCHAR(64) NOT NULL,
    target_id VARCHAR(128) NOT NULL,
    change_type VARCHAR(64) NOT NULL,
    risk_level VARCHAR(16) NOT NULL,
    reason LONGTEXT NOT NULL,
    validation_evidence LONGTEXT NOT NULL,
    rollback_plan LONGTEXT NOT NULL,
    change_status VARCHAR(32) NOT NULL,
    requested_by VARCHAR(128) NOT NULL,
    approved_by VARCHAR(128) NULL,
    requested_at TIMESTAMP(6) NOT NULL,
    approved_at TIMESTAMP(6) NULL,
    executed_at TIMESTAMP(6) NULL,
    rolled_back_at TIMESTAMP(6) NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uk_governance_changes_change_id (change_id),
    KEY idx_governance_changes_status (change_status),
    KEY idx_governance_changes_target (target_type, target_id)
);

CREATE TABLE red_team_test_runs (
    id BIGINT NOT NULL AUTO_INCREMENT,
    test_id VARCHAR(128) NOT NULL,
    release_id VARCHAR(128) NOT NULL,
    test_type VARCHAR(64) NOT NULL,
    dataset_version VARCHAR(128) NOT NULL,
    case_count INT NOT NULL,
    blocked_count INT NOT NULL,
    escaped_count INT NOT NULL,
    severity VARCHAR(16) NOT NULL,
    report_uri VARCHAR(2048) NOT NULL,
    test_status VARCHAR(32) NOT NULL,
    executed_by VARCHAR(128) NOT NULL,
    executed_at TIMESTAMP(6) NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uk_red_team_test_id (test_id),
    KEY idx_red_team_release_status (release_id, test_status),
    KEY idx_red_team_executed_at (executed_at)
);

CREATE TABLE rollback_drill_runs (
    id BIGINT NOT NULL AUTO_INCREMENT,
    drill_id VARCHAR(128) NOT NULL,
    release_id VARCHAR(128) NOT NULL,
    rollback_target_release_id VARCHAR(128) NOT NULL,
    drill_status VARCHAR(32) NOT NULL,
    recovery_duration_seconds INT NOT NULL,
    evidence_uri VARCHAR(2048) NOT NULL,
    data_integrity_check BOOLEAN NOT NULL,
    drilled_by VARCHAR(128) NOT NULL,
    drilled_at TIMESTAMP(6) NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uk_rollback_drill_id (drill_id),
    KEY idx_rollback_drill_release_time (release_id, drilled_at),
    KEY idx_rollback_drill_status (drill_status)
);

CREATE TABLE model_monitoring_snapshots (
    id BIGINT NOT NULL AUTO_INCREMENT,
    snapshot_id VARCHAR(128) NOT NULL,
    release_id VARCHAR(128) NOT NULL,
    window_start TIMESTAMP(6) NOT NULL,
    window_end TIMESTAMP(6) NOT NULL,
    drift_metric VARCHAR(64) NOT NULL,
    drift_score DOUBLE NOT NULL,
    drift_threshold DOUBLE NOT NULL,
    gpu_utilization_p95 DOUBLE NOT NULL,
    gpu_memory_p95_mb DOUBLE NOT NULL,
    queue_latency_p95_ms DOUBLE NOT NULL,
    capacity_baseline_json LONGTEXT NOT NULL,
    monitoring_status VARCHAR(32) NOT NULL,
    action_taken LONGTEXT NOT NULL,
    observed_by VARCHAR(128) NOT NULL,
    observed_at TIMESTAMP(6) NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uk_model_monitoring_snapshot_id (snapshot_id),
    KEY idx_monitoring_release_observed (release_id, observed_at),
    KEY idx_monitoring_status (monitoring_status)
);

CREATE TABLE safety_incidents (
    id BIGINT NOT NULL AUTO_INCREMENT,
    incident_id VARCHAR(128) NOT NULL,
    release_id VARCHAR(128) NOT NULL,
    incident_type VARCHAR(64) NOT NULL,
    severity VARCHAR(16) NOT NULL,
    summary LONGTEXT NOT NULL,
    root_cause LONGTEXT NULL,
    corrective_action LONGTEXT NULL,
    incident_status VARCHAR(32) NOT NULL,
    owner VARCHAR(128) NOT NULL,
    detected_at TIMESTAMP(6) NOT NULL,
    due_at TIMESTAMP(6) NULL,
    closed_at TIMESTAMP(6) NULL,
    evidence_uri VARCHAR(2048) NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uk_safety_incident_id (incident_id),
    KEY idx_safety_incident_status (incident_status),
    KEY idx_safety_incident_release (release_id, detected_at)
);
