"""Additional source-traceable public-health documents.

The rows below are concise, non-prescriptive summaries of official pages.  They
are intentionally limited to symptoms, risk context, and escalation signals so
the corpus cannot be mistaken for a prescribing protocol.
"""
from __future__ import annotations


_ROWS: tuple[tuple[str, str, str, str, str, str, str, str], ...] = (
    # Cardiovascular medicine (25 documents)
    (
        "card-rheumatic-heart-disease",
        "心血管内科",
        "World Health Organization",
        "Rheumatic heart disease",
        "https://www.who.int/news-room/fact-sheets/detail/rheumatic-heart-disease",
        "2025-01-24",
        "CC BY-NC-SA 3.0 IGO",
        "风湿性心脏病通常与链球菌感染后的风湿热有关，可累及心脏瓣膜。活动耐量下降、心悸、胸闷、气短或下肢水肿需要心血管内科评估；突发严重呼吸困难、晕厥或持续胸痛应立即就医。",
    ),
    (
        "card-salt-reduction",
        "心血管内科",
        "World Health Organization",
        "Sodium reduction",
        "https://www.who.int/news-room/fact-sheets/detail/salt-reduction",
        "2023-03-09",
        "CC BY-NC-SA 3.0 IGO",
        "长期摄入过多钠会增加血压升高和心血管疾病风险。减少高盐加工食品、查看食品标签并保持规律血压监测有助于风险管理；出现胸痛、气短或神经功能异常时不能仅归因于饮食，应及时就医。",
    ),
    (
        "card-physical-activity",
        "心血管内科",
        "World Health Organization",
        "Physical activity",
        "https://www.who.int/news-room/fact-sheets/detail/physical-activity",
        "2024-06-26",
        "CC BY-NC-SA 3.0 IGO",
        "规律身体活动有助于心血管健康，久坐和活动耐量下降应纳入健康评估。活动过程中出现胸部不适、明显气短、头晕或晕厥，应立即停止并接受专业评估。",
    ),
    (
        "card-healthy-diet",
        "心血管内科",
        "World Health Organization",
        "Healthy diet",
        "https://www.who.int/news-room/fact-sheets/detail/healthy-diet",
        "2020-04-29",
        "CC BY-NC-SA 3.0 IGO",
        "健康饮食强调多样化食物、蔬菜水果、豆类、全谷物和坚果，并减少高盐、游离糖、饱和脂肪和反式脂肪。已有高血压、血脂异常或糖代谢问题者，应将饮食记录带给医生综合评估。",
    ),
    (
        "card-tobacco",
        "心血管内科",
        "World Health Organization",
        "Tobacco and nicotine",
        "https://www.who.int/news-room/fact-sheets/detail/tobacco",
        "2024-07-31",
        "CC BY-NC-SA 3.0 IGO",
        "烟草暴露会增加冠心病和卒中等心血管疾病风险，二手烟也会造成危害。戒烟支持应结合个人情况由专业人员提供；出现胸痛、呼吸困难或突发神经症状时应优先急诊评估。",
    ),
    (
        "card-alcohol",
        "心血管内科",
        "World Health Organization",
        "Alcohol",
        "https://www.who.int/news-room/fact-sheets/detail/alcohol",
        "2024-06-28",
        "CC BY-NC-SA 3.0 IGO",
        "酒精使用与高血压、心律失常和多种心血管疾病风险相关。减少或避免饮酒有助于风险管理；心悸伴胸痛、气短、头晕或晕厥时应及时线下就医。",
    ),
    (
        "card-diabetes",
        "心血管内科",
        "World Health Organization",
        "Diabetes",
        "https://www.who.int/news-room/fact-sheets/detail/diabetes",
        "2023-04-05",
        "CC BY-NC-SA 3.0 IGO",
        "糖尿病长期血糖异常会增加心血管、肾脏、眼部和神经并发症风险。口渴多尿、乏力或视物异常需要医疗评估；意识改变、严重脱水或胸痛属于急症信号。",
    ),
    (
        "card-obesity-overweight",
        "心血管内科",
        "World Health Organization",
        "Obesity and overweight",
        "https://www.who.int/news-room/fact-sheets/detail/obesity-and-overweight",
        "2024-03-01",
        "CC BY-NC-SA 3.0 IGO",
        "超重或肥胖与高血压、冠心病、卒中和糖代谢异常风险增加有关。体重变化、腰围、血压和活动耐量应结合整体健康状况评估；突发胸痛或呼吸困难不能仅归因于体重。",
    ),
    (
        "card-chagas-disease",
        "心血管内科",
        "World Health Organization",
        "Chagas disease (American trypanosomiasis)",
        "https://www.who.int/health-topics/chagas-disease",
        "2020-02-04",
        "CC BY-NC-SA 3.0 IGO",
        "恰加斯病的慢性期可能累及心肌并导致心律失常或心功能问题。曾在流行地区居住、输血或有相关暴露史且出现心悸、晕厥、气短者，应向医生说明暴露史并接受评估。",
    ),
    (
        "card-coronary-heart-disease",
        "心血管内科",
        "National Heart, Lung, and Blood Institute",
        "Coronary Heart Disease",
        "https://www.nhlbi.nih.gov/health/coronary-heart-disease",
        "2022-03-24",
        "U.S. Government work; public domain unless otherwise noted",
        "冠状动脉粥样斑块可减少心肌供血，活动时胸部压迫、气短或疲劳可能提示需要评估。胸部不适持续或伴冷汗、恶心、晕厥时，应立即呼叫急救。",
    ),
    (
        "card-heart-attack-nhlbi",
        "心血管内科",
        "National Heart, Lung, and Blood Institute",
        "Heart Attack",
        "https://www.nhlbi.nih.gov/health/heart-attack",
        "2022-03-24",
        "U.S. Government work; public domain unless otherwise noted",
        "心肌梗死常表现为胸部压迫或疼痛，也可放射至手臂、背部、颈部或下颌，并伴气短、出汗、恶心或头晕。症状突然出现或持续不缓解时应立即急诊，避免自行驾车。",
    ),
    (
        "card-heart-failure-nhlbi",
        "心血管内科",
        "National Heart, Lung, and Blood Institute",
        "Heart Failure",
        "https://www.nhlbi.nih.gov/health/heart-failure",
        "2022-03-24",
        "U.S. Government work; public domain unless otherwise noted",
        "心力衰竭可导致活动后气短、乏力、夜间平卧困难和下肢水肿。症状逐渐加重或影响日常活动应尽快评估；突发严重气短、粉红色泡沫痰或意识改变属于急症。",
    ),
    (
        "card-arrhythmias-nhlbi",
        "心血管内科",
        "National Heart, Lung, and Blood Institute",
        "Arrhythmias",
        "https://www.nhlbi.nih.gov/health/arrhythmias",
        "2022-03-24",
        "U.S. Government work; public domain unless otherwise noted",
        "心律失常可表现为心跳过快、过慢或不规则，伴心悸、乏力、头晕或晕厥。记录发作时间和诱因有助于评估；心悸伴胸痛、严重气短或晕厥时应立即就医。",
    ),
    (
        "card-peripheral-artery-disease",
        "心血管内科",
        "National Heart, Lung, and Blood Institute",
        "Peripheral Artery Disease",
        "https://www.nhlbi.nih.gov/health/peripheral-artery-disease",
        "2022-03-24",
        "U.S. Government work; public domain unless otherwise noted",
        "外周动脉疾病可引起行走时小腿疼痛、肢体发凉或麻木，休息后缓解并不代表无需评估。肢体突然苍白、冰冷、剧痛或感觉运动明显下降时应立即急诊。",
    ),
    (
        "card-high-blood-pressure-nhlbi",
        "心血管内科",
        "National Heart, Lung, and Blood Institute",
        "High Blood Pressure",
        "https://www.nhlbi.nih.gov/health/high-blood-pressure",
        "2022-03-24",
        "U.S. Government work; public domain unless otherwise noted",
        "高血压常无明显症状，需要规范测量和连续记录才能判断控制情况。血压异常伴剧烈头痛、胸痛、气短、视物异常或意识改变时，应接受紧急评估。",
    ),
    (
        "card-angina-medlineplus",
        "心血管内科",
        "U.S. National Library of Medicine",
        "Angina",
        "https://medlineplus.gov/angina.html",
        "2025-03-17",
        "U.S. Government work; public domain unless otherwise noted",
        "心绞痛常表现为胸部压迫、紧缩或疼痛，可能在活动或情绪紧张时出现。新出现、频率增加、持续时间延长或静息时发生的胸痛，应立即进行急诊评估。",
    ),
    (
        "card-heart-valve-diseases-medlineplus",
        "心血管内科",
        "U.S. National Library of Medicine",
        "Heart Valve Diseases",
        "https://medlineplus.gov/heartvalvediseases.html",
        "2025-03-17",
        "U.S. Government work; public domain unless otherwise noted",
        "心脏瓣膜疾病可能引起气短、乏力、胸部不适、心悸或下肢水肿。症状持续或活动耐量下降需要心血管评估；突发严重气短、晕厥或胸痛应急诊。",
    ),
    (
        "card-heart-attack-medlineplus",
        "心血管内科",
        "U.S. National Library of Medicine",
        "Heart Attack",
        "https://medlineplus.gov/heartattack.html",
        "2025-03-17",
        "U.S. Government work; public domain unless otherwise noted",
        "心肌梗死的警示表现包括胸部压迫或疼痛、上肢或下颌放射痛、气短、冷汗和恶心。女性、老年人或糖尿病患者的表现可能不典型，但出现突发不适仍应立即求助。",
    ),
    (
        "card-heart-failure-medlineplus",
        "心血管内科",
        "U.S. National Library of Medicine",
        "Heart Failure",
        "https://medlineplus.gov/heartfailure.html",
        "2025-03-17",
        "U.S. Government work; public domain unless otherwise noted",
        "心力衰竭可出现活动后气短、夜间憋醒、乏力和脚踝水肿。体重或水肿快速变化、呼吸困难加重或无法平卧时，应尽快联系医生；严重气短需急诊。",
    ),
    (
        "card-high-blood-pressure-medlineplus",
        "心血管内科",
        "U.S. National Library of Medicine",
        "High Blood Pressure",
        "https://medlineplus.gov/highbloodpressure.html",
        "2025-03-17",
        "U.S. Government work; public domain unless otherwise noted",
        "高血压通常没有明显症状，不能仅凭感觉判断是否控制良好。持续记录测量结果有助于医生评估；伴神经功能改变、胸痛或呼吸困难时应紧急就医。",
    ),
    (
        "card-cholesterol-medlineplus",
        "心血管内科",
        "U.S. National Library of Medicine",
        "Cholesterol",
        "https://medlineplus.gov/cholesterol.html",
        "2025-03-17",
        "U.S. Government work; public domain unless otherwise noted",
        "高胆固醇通常没有症状，需要结合血液检测和整体心血管风险评估。胸痛、活动后气短或突发言语和肢体异常不是普通化验问题，应及时就医。",
    ),
    (
        "card-stroke-medlineplus",
        "心血管内科",
        "U.S. National Library of Medicine",
        "Stroke",
        "https://medlineplus.gov/stroke.html",
        "2025-03-17",
        "U.S. Government work; public domain unless otherwise noted",
        "卒中可突然出现面部不对称、单侧肢体无力或麻木、言语含糊、视物异常、平衡障碍或剧烈头痛。即使症状自行缓解也应立即急诊，因为时间对评估和处理很重要。",
    ),
    (
        "card-peripheral-artery-medlineplus",
        "心血管内科",
        "U.S. National Library of Medicine",
        "Peripheral Artery Disease",
        "https://medlineplus.gov/peripheralarterialdisease.html",
        "2025-03-17",
        "U.S. Government work; public domain unless otherwise noted",
        "外周动脉疾病常见于下肢，可能表现为行走时疼痛、麻木、皮肤发凉或伤口愈合不良。静息痛、皮肤颜色明显改变或肢体突然冰冷需要尽快线下评估。",
    ),
    (
        "card-palpitations-nhs",
        "心血管内科",
        "National Health Service",
        "Heart palpitations",
        "https://www.nhs.uk/conditions/heart-palpitations/",
        "2025-01-01",
        "Open Government Licence v3.0",
        "心悸是对心跳加快、跳动有力或不规则的主观感受，可能与压力、睡眠不足或其他因素有关。若心悸持续不缓解，或伴胸痛、气短、头晕、晕厥，应立即就医。",
    ),
    (
        "card-heart-attack-nhs",
        "心血管内科",
        "National Health Service",
        "Heart attack",
        "https://www.nhs.uk/conditions/heart-attack/",
        "2026-08-07",
        "Open Government Licence v3.0",
        "心肌梗死可表现为胸部压迫或紧缩，疼痛向手臂、颈部、下颌或背部放射，并伴气短、出汗或恶心。疑似心肌梗死应立即呼叫急救，不要自行驾车。",
    ),

    # Respiratory medicine (25 documents)
    (
        "resp-tuberculosis-who",
        "呼吸内科",
        "World Health Organization",
        "Tuberculosis",
        "https://www.who.int/news-room/fact-sheets/detail/tuberculosis",
        "2025-02-21",
        "CC BY-NC-SA 3.0 IGO",
        "结核病可表现为持续咳嗽、发热、夜间出汗、乏力或体重下降，部分患者会咯血。症状持续或有密切接触史应尽快就医并说明暴露情况；大量咯血或呼吸困难需急诊。",
    ),
    (
        "resp-pneumonia-nhlbi",
        "呼吸内科",
        "National Heart, Lung, and Blood Institute",
        "Pneumonia - What Is Pneumonia?",
        "https://www.nhlbi.nih.gov/health/pneumonia",
        "2022-03-24",
        "U.S. Government work; public domain unless otherwise noted",
        "肺炎可出现咳嗽、发热、寒战、气短和胸痛，儿童、老年人及慢性病患者风险更高。呼吸明显费力、口唇发紫、意识改变或无法进食饮水时应立即就医。",
    ),
    (
        "resp-influenza-seasonal-who",
        "呼吸内科",
        "World Health Organization",
        "Influenza (seasonal)",
        "https://www.who.int/news-room/fact-sheets/detail/influenza-(seasonal)",
        "2025-06-27",
        "CC BY-NC-SA 3.0 IGO",
        "流感通常起病较急，可有发热、咳嗽、咽痛、肌肉酸痛、头痛和乏力。高风险人群症状加重、出现气短、胸痛、意识改变或持续高热时应及时评估。",
    ),
    (
        "resp-covid19-who",
        "呼吸内科",
        "World Health Organization",
        "Coronavirus disease (COVID-19)",
        "https://www.who.int/news-room/fact-sheets/detail/coronavirus-disease-(covid-19)",
        "2025-08-27",
        "CC BY-NC-SA 3.0 IGO",
        "新冠感染可有发热、咳嗽、咽痛、乏力、肌肉酸痛或嗅味觉变化，症状轻重差异较大。呼吸困难、持续胸部压迫、意识改变或口唇发紫是需要立即就医的危险信号。",
    ),
    (
        "resp-household-air-pollution",
        "呼吸内科",
        "World Health Organization",
        "Household air pollution and health",
        "https://www.who.int/news-room/fact-sheets/detail/household-air-pollution-and-health",
        "2025-06-16",
        "CC BY-NC-SA 3.0 IGO",
        "室内燃料和烟雾产生的空气污染会增加呼吸道感染、慢性阻塞性肺疾病和哮喘等风险。反复咳嗽或气短应结合居住和工作暴露进行评估；严重呼吸困难需急诊。",
    ),
    (
        "resp-ambient-air-pollution",
        "呼吸内科",
        "World Health Organization",
        "Ambient (outdoor) air pollution",
        "https://www.who.int/news-room/fact-sheets/detail/ambient-(outdoor)-air-quality-and-health",
        "2024-10-24",
        "CC BY-NC-SA 3.0 IGO",
        "细颗粒物等室外空气污染物可加重哮喘、慢阻肺和心肺疾病。空气质量较差时应关注咳嗽、喘息和气短变化；胸痛、口唇发紫或呼吸困难加重应立即就医。",
    ),
    (
        "resp-asthma-nhlbi",
        "呼吸内科",
        "National Heart, Lung, and Blood Institute",
        "Asthma",
        "https://www.nhlbi.nih.gov/health/asthma",
        "2022-03-24",
        "U.S. Government work; public domain unless otherwise noted",
        "哮喘症状可反复波动，常见喘息、咳嗽、胸闷和气短，并可能受过敏原、运动或感染诱发。说话困难、呼吸费力、口唇发紫或意识异常时应立即急诊。",
    ),
    (
        "resp-copd-nhlbi",
        "呼吸内科",
        "National Heart, Lung, and Blood Institute",
        "Chronic Obstructive Pulmonary Disease (COPD)",
        "https://www.nhlbi.nih.gov/health/copd",
        "2022-03-24",
        "U.S. Government work; public domain unless otherwise noted",
        "慢阻肺可出现长期咳嗽、咳痰和活动后气短，吸烟或粉尘暴露史有助于医生判断风险。症状突然加重、无法完整说话、胸痛或意识改变需要紧急评估。",
    ),
    (
        "resp-sleep-apnea-nhlbi",
        "呼吸内科",
        "National Heart, Lung, and Blood Institute",
        "Sleep Apnea",
        "https://www.nhlbi.nih.gov/health/sleep-apnea",
        "2022-03-24",
        "U.S. Government work; public domain unless otherwise noted",
        "睡眠呼吸暂停可表现为打鼾、睡眠中呼吸暂停或憋醒、晨起头痛和白天嗜睡。夜间反复窒息感或白天困倦影响驾驶和工作时，应尽快接受睡眠与呼吸评估。",
    ),
    (
        "resp-pulmonary-hypertension-nhlbi",
        "呼吸内科",
        "National Heart, Lung, and Blood Institute",
        "Pulmonary Hypertension",
        "https://www.nhlbi.nih.gov/health/pulmonary-hypertension",
        "2022-03-24",
        "U.S. Government work; public domain unless otherwise noted",
        "肺动脉高压可引起活动后气短、疲劳、胸部不适、心悸或晕厥。症状逐渐加重需要专科评估；突发严重气短、胸痛或晕厥应立即就医。",
    ),
    (
        "resp-pulmonary-embolism-nhlbi",
        "呼吸内科",
        "National Heart, Lung, and Blood Institute",
        "Pulmonary Embolism",
        "https://www.nhlbi.nih.gov/health/pulmonary-embolism",
        "2022-03-24",
        "U.S. Government work; public domain unless otherwise noted",
        "肺栓塞可突然出现气短、胸痛、心跳加快、咯血或晕厥，尤其要结合近期手术、长期卧床或下肢肿痛等情况。疑似肺栓塞属于急症，应立即呼叫急救。",
    ),
    (
        "resp-bronchitis-medlineplus",
        "呼吸内科",
        "U.S. National Library of Medicine",
        "Bronchitis",
        "https://medlineplus.gov/bronchitis.html",
        "2025-01-15",
        "U.S. Government work; public domain unless otherwise noted",
        "支气管炎常表现为咳嗽，可伴咳痰、喘息或胸部不适。咳嗽持续不缓解、反复发作、伴高热、咯血或呼吸困难时，应接受呼吸专科评估。",
    ),
    (
        "resp-pneumonia-medlineplus",
        "呼吸内科",
        "U.S. National Library of Medicine",
        "Pneumonia",
        "https://medlineplus.gov/pneumonia.html",
        "2025-01-15",
        "U.S. Government work; public domain unless otherwise noted",
        "肺炎可出现发热、咳嗽、咳痰、气短、寒战或胸痛。老年人可能主要表现为乏力或意识改变；呼吸费力、口唇发紫或无法进食饮水时应立即就医。",
    ),
    (
        "resp-asthma-medlineplus",
        "呼吸内科",
        "U.S. National Library of Medicine",
        "Asthma",
        "https://medlineplus.gov/asthma.html",
        "2025-01-15",
        "U.S. Government work; public domain unless otherwise noted",
        "哮喘可反复出现喘息、咳嗽、胸闷和气短，夜间、运动后或接触刺激因素时可能加重。发作时不能完整说话、呼吸迅速恶化或出现发绀时需立即急诊。",
    ),
    (
        "resp-copd-medlineplus",
        "呼吸内科",
        "U.S. National Library of Medicine",
        "COPD",
        "https://medlineplus.gov/copd.html",
        "2025-01-15",
        "U.S. Government work; public domain unless otherwise noted",
        "慢阻肺常见长期咳嗽、咳痰、喘息和活动后气短，吸烟史和暴露史应如实告知医生。症状突然加重、胸痛、意识改变或严重呼吸困难需要急诊。",
    ),
    (
        "resp-rsv-medlineplus",
        "呼吸内科",
        "U.S. National Library of Medicine",
        "Respiratory Syncytial Virus Infections",
        "https://medlineplus.gov/respiratorysyncytialvirusinfections.html",
        "2025-01-15",
        "U.S. Government work; public domain unless otherwise noted",
        "呼吸道合胞病毒感染可有流涕、咳嗽、喘息和发热，婴幼儿、老年人和基础病患者可能进展为下呼吸道疾病。进食减少、呼吸费力、发绀或精神反应差时应立即就医。",
    ),
    (
        "resp-tuberculosis-medlineplus",
        "呼吸内科",
        "U.S. National Library of Medicine",
        "Tuberculosis",
        "https://medlineplus.gov/tuberculosis.html",
        "2025-01-15",
        "U.S. Government work; public domain unless otherwise noted",
        "结核病可表现为持续咳嗽、发热、夜间出汗、乏力和体重下降，部分患者会咯血。应主动告知密切接触和既往感染史；咯血量增加或呼吸困难需急诊。",
    ),
    (
        "resp-flu-medlineplus",
        "呼吸内科",
        "U.S. National Library of Medicine",
        "Flu",
        "https://medlineplus.gov/flu.html",
        "2025-01-15",
        "U.S. Government work; public domain unless otherwise noted",
        "流感常突然出现发热、咳嗽、咽痛、肌肉酸痛、头痛和明显乏力。高风险人群出现气短、胸痛、意识改变、持续高热或脱水表现时应及时就医。",
    ),
    (
        "resp-sleep-apnea-medlineplus",
        "呼吸内科",
        "U.S. National Library of Medicine",
        "Sleep Apnea",
        "https://medlineplus.gov/sleepapnea.html",
        "2025-01-15",
        "U.S. Government work; public domain unless otherwise noted",
        "睡眠呼吸暂停可表现为大声打鼾、睡眠中呼吸暂停、憋醒、晨起头痛和白天嗜睡。白天困倦影响驾驶，或夜间反复出现窒息感时，应接受专业评估。",
    ),
    (
        "resp-cough-nhs",
        "呼吸内科",
        "National Health Service",
        "Cough",
        "https://www.nhs.uk/conditions/cough/",
        "2025-01-01",
        "Open Government Licence v3.0",
        "咳嗽常见于感染或气道刺激，但持续时间、咳痰颜色和伴随症状有助于判断是否需要就医。咳嗽超过数周、咯血、胸痛、体重下降或呼吸困难应尽快评估。",
    ),
    (
        "resp-shortness-of-breath-nhs",
        "呼吸内科",
        "National Health Service",
        "Shortness of breath",
        "https://www.nhs.uk/conditions/shortness-of-breath/",
        "2025-01-01",
        "Open Government Licence v3.0",
        "气短需要结合发生时间、活动关系、胸痛、咳嗽和既往心肺疾病判断。突然严重气短、不能完整说话、胸部压迫、口唇发紫或意识改变时应立即呼叫急救。",
    ),
    (
        "resp-asthma-nhs",
        "呼吸内科",
        "National Health Service",
        "Asthma",
        "https://www.nhs.uk/conditions/asthma/",
        "2025-01-01",
        "Open Government Licence v3.0",
        "哮喘可反复出现喘息、咳嗽、胸闷和气短，夜间或清晨以及接触诱因后可能加重。发作迅速恶化、说话困难、口唇发紫或意识异常时应立即就医。",
    ),
    (
        "resp-copd-nhs",
        "呼吸内科",
        "National Health Service",
        "Chronic obstructive pulmonary disease (COPD)",
        "https://www.nhs.uk/conditions/chronic-obstructive-pulmonary-disease-copd/",
        "2025-01-01",
        "Open Government Licence v3.0",
        "慢阻肺可造成长期咳嗽、咳痰、喘息和活动后气短，症状常逐渐进展。气短突然加重、胸痛、咯血、发绀或意识改变时应立即急诊。",
    ),
    (
        "resp-pneumonia-nhs",
        "呼吸内科",
        "National Health Service",
        "Pneumonia",
        "https://www.nhs.uk/conditions/pneumonia/",
        "2025-01-01",
        "Open Government Licence v3.0",
        "肺炎常见咳嗽、发热、气短和胸痛，老年人可能出现乏力或意识改变。呼吸困难、持续胸痛、发绀、明显嗜睡或无法补充水分时应及时就医。",
    ),
    (
        "resp-bronchitis-nhs",
        "呼吸内科",
        "National Health Service",
        "Bronchitis",
        "https://www.nhs.uk/conditions/bronchitis/",
        "2025-01-01",
        "Open Government Licence v3.0",
        "急性支气管炎常有咳嗽、咳痰、咽痛或胸部不适。咳嗽迁延、咯血、胸痛、呼吸困难或症状影响日常活动时，应接受线下评估。",
    ),

    # Gastroenterology (25 documents)
    (
        "gast-constipation-niddk",
        "消化内科",
        "National Institute of Diabetes and Digestive and Kidney Diseases",
        "Symptoms & Causes of Constipation",
        "https://www.niddk.nih.gov/health-information/digestive-diseases/constipation/symptoms-causes",
        "2026-03-18",
        "U.S. Government work; public domain unless otherwise noted",
        "便秘可表现为排便次数减少、粪便干硬、排便费力或排便不尽感。便血、持续腹痛、呕吐、明显腹胀、体重下降或无法排气时应尽快就医。",
    ),
    (
        "gast-ibs-niddk",
        "消化内科",
        "National Institute of Diabetes and Digestive and Kidney Diseases",
        "Symptoms & Causes of Irritable Bowel Syndrome",
        "https://www.niddk.nih.gov/health-information/digestive-diseases/irritable-bowel-syndrome",
        "2026-03-18",
        "U.S. Government work; public domain unless otherwise noted",
        "肠易激综合征常见反复腹痛并伴排便习惯改变、腹胀或排便后症状变化。便血、发热、夜间症状、贫血或体重下降不是普通功能性不适的典型表现，应尽快评估。",
    ),
    (
        "gast-crohns-niddk",
        "消化内科",
        "National Institute of Diabetes and Digestive and Kidney Diseases",
        "Crohn's Disease",
        "https://www.niddk.nih.gov/health-information/digestive-diseases/crohns-disease",
        "2026-03-18",
        "U.S. Government work; public domain unless otherwise noted",
        "克罗恩病可有腹痛、腹泻、乏力、发热和体重下降，也可能出现肛周或关节症状。持续便血、剧烈腹痛、脱水或高热时需要尽快接受消化专科评估。",
    ),
    (
        "gast-ulcerative-colitis-niddk",
        "消化内科",
        "National Institute of Diabetes and Digestive and Kidney Diseases",
        "Ulcerative Colitis",
        "https://www.niddk.nih.gov/health-information/digestive-diseases/ulcerative-colitis",
        "2026-03-18",
        "U.S. Government work; public domain unless otherwise noted",
        "溃疡性结肠炎可出现反复血性腹泻、便意急迫、腹痛和乏力。大量出血、持续高热、明显腹胀、脱水或意识改变时应立即就医。",
    ),
    (
        "gast-celiac-niddk",
        "消化内科",
        "National Institute of Diabetes and Digestive and Kidney Diseases",
        "Symptoms & Causes of Celiac Disease",
        "https://www.niddk.nih.gov/health-information/digestive-diseases/celiac-disease/symptoms-causes",
        "2026-03-18",
        "U.S. Government work; public domain unless otherwise noted",
        "乳糜泻可能表现为腹泻、腹胀、腹痛、体重下降、贫血或疲劳，儿童还可能出现生长问题。持续症状、营养不良或反复缺铁需要由医生进行规范检查。",
    ),
    (
        "gast-lactose-intolerance-niddk",
        "消化内科",
        "National Institute of Diabetes and Digestive and Kidney Diseases",
        "Symptoms & Causes of Lactose Intolerance",
        "https://www.niddk.nih.gov/health-information/digestive-diseases/lactose-intolerance/symptoms-causes",
        "2026-03-18",
        "U.S. Government work; public domain unless otherwise noted",
        "乳糖不耐受可在摄入乳制品后出现腹胀、腹痛、肠鸣、排气增多或腹泻。症状反复或影响营养摄入时，应由医生鉴别其他消化系统疾病。",
    ),
    (
        "gast-gallstones-niddk",
        "消化内科",
        "National Institute of Diabetes and Digestive and Kidney Diseases",
        "Symptoms & Causes of Gallstones",
        "https://www.niddk.nih.gov/health-information/digestive-diseases/gallstones/symptoms-causes",
        "2026-03-18",
        "U.S. Government work; public domain unless otherwise noted",
        "胆结石发作可表现为右上腹或上腹持续疼痛、恶心和呕吐，常需要结合进食和疼痛持续时间评估。发热、黄疸、尿色明显变深或持续剧痛时应立即就医。",
    ),
    (
        "gast-hemorrhoids-niddk",
        "消化内科",
        "National Institute of Diabetes and Digestive and Kidney Diseases",
        "Symptoms & Causes of Hemorrhoids",
        "https://www.niddk.nih.gov/health-information/digestive-diseases/hemorrhoids/symptoms-causes",
        "2026-03-18",
        "U.S. Government work; public domain unless otherwise noted",
        "痔可造成便后鲜红色出血、肛门瘙痒、疼痛或脱出。反复出血、黑便、明显头晕、剧烈疼痛或排便习惯改变需要医生排除其他原因。",
    ),
    (
        "gast-peptic-ulcer-medlineplus",
        "消化内科",
        "U.S. National Library of Medicine",
        "Stomach Ulcer | Peptic Ulcer | MedlinePlus",
        "https://medlineplus.gov/pepticulcer.html",
        "2026-03-18",
        "U.S. Government work; public domain unless otherwise noted",
        "消化性溃疡可引起上腹部疼痛、饱胀、恶心或食欲下降。呕血、黑便、突发剧烈腹痛、头晕或晕厥提示消化道出血或穿孔风险，应立即急诊。",
    ),
    (
        "gast-viral-gastroenteritis-niddk",
        "消化内科",
        "National Institute of Diabetes and Digestive and Kidney Diseases",
        "Symptoms & Causes of Viral Gastroenteritis",
        "https://www.niddk.nih.gov/health-information/digestive-diseases/viral-gastroenteritis/symptoms-causes",
        "2026-03-18",
        "U.S. Government work; public domain unless otherwise noted",
        "病毒性胃肠炎常突然出现呕吐、水样腹泻、腹部痉挛和恶心。口干、尿量减少、明显乏力、血便、持续高热或意识改变提示需要及时就医。",
    ),
    (
        "gast-diverticular-niddk",
        "消化内科",
        "National Institute of Diabetes and Digestive and Kidney Diseases",
        "Symptoms & Causes of Diverticular Disease",
        "https://www.niddk.nih.gov/health-information/digestive-diseases/diverticulosis-diverticulitis/symptoms-causes",
        "2026-03-18",
        "U.S. Government work; public domain unless otherwise noted",
        "憩室病可能没有症状，也可能出现下腹痛、排便改变或便血；憩室炎常伴持续腹痛、发热和恶心。大量出血、剧烈腹痛、呕吐或腹部明显僵硬时应急诊。",
    ),
    (
        "gast-nafld-niddk",
        "消化内科",
        "National Institute of Diabetes and Digestive and Kidney Diseases",
        "Symptoms & Causes of NAFLD & NASH",
        "https://www.niddk.nih.gov/health-information/liver-disease/nafld-nash",
        "2026-03-18",
        "U.S. Government work; public domain unless otherwise noted",
        "非酒精性脂肪性肝病早期常无明显症状，部分人有乏力或右上腹不适，常与体重和代谢风险相关。黄疸、腹部明显膨隆、意识改变或出血倾向需要及时评估。",
    ),
    (
        "gast-pancreatitis-niddk",
        "消化内科",
        "National Institute of Diabetes and Digestive and Kidney Diseases",
        "Symptoms & Causes of Pancreatitis",
        "https://www.niddk.nih.gov/health-information/digestive-diseases/pancreatitis/symptoms-causes",
        "2026-03-18",
        "U.S. Government work; public domain unless otherwise noted",
        "胰腺炎常表现为上腹部持续疼痛，可向背部放射，并伴恶心、呕吐或发热。疼痛剧烈不缓解、反复呕吐、腹胀、心跳加快或意识改变时应立即就医。",
    ),
    (
        "gast-gi-bleeding-niddk",
        "消化内科",
        "National Institute of Diabetes and Digestive and Kidney Diseases",
        "Symptoms & Causes of GI Bleeding",
        "https://www.niddk.nih.gov/health-information/digestive-diseases/gastrointestinal-bleeding",
        "2026-03-18",
        "U.S. Government work; public domain unless otherwise noted",
        "消化道出血可表现为呕血、咖啡色样呕吐物、黑便或鲜红色便，也可能只有乏力和头晕。出现晕厥、面色苍白、心跳明显加快或大量出血时应立即急诊。",
    ),
    (
        "gast-food-safety-who",
        "消化内科",
        "World Health Organization",
        "Food safety",
        "https://www.who.int/news-room/fact-sheets/detail/food-safety",
        "2024-05-30",
        "CC BY-NC-SA 3.0 IGO",
        "受污染的食物和饮水可传播多种胃肠道感染。处理食物时应注意清洁、分开生熟、充分加热和安全储存；进食后出现持续呕吐、血便、高热或脱水表现时应就医。",
    ),
    (
        "gast-ibs-medlineplus",
        "消化内科",
        "U.S. National Library of Medicine",
        "Irritable Bowel Syndrome",
        "https://medlineplus.gov/irritablebowelsyndrome.html",
        "2025-03-17",
        "U.S. Government work; public domain unless otherwise noted",
        "肠易激综合征可有反复腹痛、腹胀以及腹泻或便秘交替。便血、发热、夜间痛醒、贫血或体重下降需要进一步检查，不能仅按功能性肠病处理。",
    ),
    (
        "gast-constipation-medlineplus",
        "消化内科",
        "U.S. National Library of Medicine",
        "Constipation",
        "https://medlineplus.gov/constipation.html",
        "2025-03-17",
        "U.S. Government work; public domain unless otherwise noted",
        "便秘表现为排便困难、粪便干硬或排便不尽感。新发且持续的便秘，伴腹痛、呕吐、便血、体重下降或无法排气时，应及时接受消化科评估。",
    ),
    (
        "gast-gallstones-medlineplus",
        "消化内科",
        "U.S. National Library of Medicine",
        "Gallstones",
        "https://medlineplus.gov/gallstones.html",
        "2025-03-17",
        "U.S. Government work; public domain unless otherwise noted",
        "胆结石可能无症状，也可造成上腹或右上腹疼痛、恶心和呕吐。疼痛持续不缓解、伴发热或黄疸时，应尽快就医排除胆道感染或梗阻。",
    ),
    (
        "gast-pancreatitis-medlineplus",
        "消化内科",
        "U.S. National Library of Medicine",
        "Pancreatitis",
        "https://medlineplus.gov/pancreatitis.html",
        "2025-03-17",
        "U.S. Government work; public domain unless otherwise noted",
        "胰腺炎常有上腹部持续疼痛并向背部放射，可伴恶心、呕吐和发热。严重疼痛、持续呕吐、腹胀或意识改变时应立即急诊。",
    ),
    (
        "gast-celiac-medlineplus",
        "消化内科",
        "U.S. National Library of Medicine",
        "Celiac Disease",
        "https://medlineplus.gov/celiacdisease.html",
        "2025-03-17",
        "U.S. Government work; public domain unless otherwise noted",
        "乳糜泻可引起慢性腹泻、腹胀、腹痛、体重下降、贫血或疲劳。长期症状或营养不良需要规范检查，避免仅凭自我饮食试验下结论。",
    ),
    (
        "gast-crohns-medlineplus",
        "消化内科",
        "U.S. National Library of Medicine",
        "Crohn Disease",
        "https://medlineplus.gov/crohnsdisease.html",
        "2025-03-17",
        "U.S. Government work; public domain unless otherwise noted",
        "克罗恩病可表现为腹痛、长期腹泻、体重下降、乏力或发热。便血、持续剧痛、脱水或高热需要及时线下评估。",
    ),
    (
        "gast-ulcerative-colitis-medlineplus",
        "消化内科",
        "U.S. National Library of Medicine",
        "Ulcerative Colitis",
        "https://medlineplus.gov/ulcerativecolitis.html",
        "2025-03-17",
        "U.S. Government work; public domain unless otherwise noted",
        "溃疡性结肠炎常见血性腹泻、便意急迫、腹痛和乏力。大量便血、持续发热、腹部明显膨胀或脱水时应立即就医。",
    ),
    (
        "gast-hepatitis-medlineplus",
        "消化内科",
        "U.S. National Library of Medicine",
        "Hepatitis",
        "https://medlineplus.gov/hepatitis.html",
        "2025-03-17",
        "U.S. Government work; public domain unless otherwise noted",
        "肝炎可能没有明显症状，也可能出现乏力、恶心、右上腹不适、尿色加深或黄疸。出现意识改变、明显出血、腹部迅速膨隆或持续呕吐时应急诊。",
    ),
    (
        "gast-hemorrhoids-medlineplus",
        "消化内科",
        "U.S. National Library of Medicine",
        "Hemorrhoids",
        "https://medlineplus.gov/hemorrhoids.html",
        "2025-03-17",
        "U.S. Government work; public domain unless otherwise noted",
        "痔可导致便后鲜血、肛门瘙痒、疼痛或肿块。反复或大量出血、黑便、明显头晕或排便习惯改变需要医生确认出血原因。",
    ),
    (
        "gast-gi-bleeding-medlineplus",
        "消化内科",
        "U.S. National Library of Medicine",
        "Gastrointestinal Bleeding",
        "https://medlineplus.gov/gastrointestinalbleeding.html",
        "2025-03-17",
        "U.S. Government work; public domain unless otherwise noted",
        "消化道出血可表现为呕血、黑便或鲜红色便，也可出现乏力、面色苍白和头晕。晕厥、心跳加快、持续出血或意识改变时应立即急诊。",
    ),

    # Dermatology (25 documents)
    (
        "derm-scabies-who",
        "皮肤科",
        "World Health Organization",
        "Scabies",
        "https://www.who.int/news-room/fact-sheets/detail/scabies",
        "2023-05-31",
        "CC BY-NC-SA 3.0 IGO",
        "疥疮常见夜间加重的剧烈瘙痒和丘疹，可在指缝、腕部、腰部等处出现皮疹。家庭或集体中多人瘙痒、出现厚痂或继发感染时，应尽快由皮肤科评估。",
    ),
    (
        "derm-psoriasis-niams",
        "皮肤科",
        "National Institute of Arthritis and Musculoskeletal and Skin Diseases",
        "Psoriasis",
        "https://www.niams.nih.gov/health-topics/psoriasis",
        "2025-06-05",
        "U.S. Government work; public domain unless otherwise noted",
        "银屑病可出现边界清楚的红斑和鳞屑斑块，常累及头皮、肘膝或躯干，也可能伴瘙痒和关节症状。皮疹迅速广泛、疼痛明显或伴发热时应及时就医。",
    ),
    (
        "derm-leprosy-who",
        "皮肤科",
        "World Health Organization",
        "Leprosy",
        "https://www.who.int/news-room/fact-sheets/detail/leprosy",
        "2023-09-08",
        "CC BY-NC-SA 3.0 IGO",
        "麻风病可表现为颜色改变或感觉减退的皮肤斑片，并可能累及周围神经。皮肤感觉持续下降、肢体无力或眼部不适需要尽快接受专科评估。",
    ),
    (
        "derm-mycetoma-who",
        "皮肤科",
        "World Health Organization",
        "Mycetoma",
        "https://www.who.int/news-room/fact-sheets/detail/mycetoma",
        "2025-10-24",
        "CC BY-NC-SA 3.0 IGO",
        "足部或其他部位长期无痛性肿胀、结节和窦道排液可能与足菌肿有关，病变可逐渐侵入深部组织。伤口扩大、疼痛、发热或行走受限时应及时专科评估。",
    ),
    (
        "derm-lymphatic-filariasis-who",
        "皮肤科",
        "World Health Organization",
        "Lymphatic filariasis",
        "https://www.who.int/news-room/fact-sheets/detail/lymphatic-filariasis",
        "2024-03-05",
        "CC BY-NC-SA 3.0 IGO",
        "淋巴丝虫病可造成肢体或生殖器持续肿胀、皮肤增厚和反复炎症，早期症状有时不明显。新发或进行性肿胀、疼痛、发热或活动受限需要线下评估。",
    ),
    (
        "derm-acne-nhs",
        "皮肤科",
        "National Health Service",
        "Acne",
        "https://www.nhs.uk/conditions/acne/",
        "2025-01-01",
        "Open Government Licence v3.0",
        "痤疮可见黑头、白头、丘疹、脓疱或结节，常累及面部、背部和胸部。疼痛性结节、明显瘢痕、突然严重加重或情绪影响明显时应皮肤科评估。",
    ),
    (
        "derm-psoriasis-nhs",
        "皮肤科",
        "National Health Service",
        "Psoriasis",
        "https://www.nhs.uk/conditions/psoriasis/",
        "2025-01-01",
        "Open Government Licence v3.0",
        "银屑病常表现为干燥、鳞屑性红斑或斑块，可伴瘙痒和关节疼痛。皮肤突然广泛发红、疼痛、起疱或伴发热时，应及时就医。",
    ),
    (
        "derm-rosacea-nhs",
        "皮肤科",
        "National Health Service",
        "Rosacea",
        "https://www.nhs.uk/conditions/rosacea/",
        "2025-01-01",
        "Open Government Licence v3.0",
        "酒渣鼻可出现面部潮红、持续发红、毛细血管明显或丘疹脓疱，眼部也可能受累。眼痛、畏光、视物模糊或症状持续进展时应尽快就医。",
    ),
    (
        "derm-contact-dermatitis-nhs",
        "皮肤科",
        "National Health Service",
        "Contact dermatitis",
        "https://www.nhs.uk/conditions/contact-dermatitis/",
        "2025-01-01",
        "Open Government Licence v3.0",
        "接触性皮炎可在接触刺激物或过敏原后出现瘙痒、红斑、脱屑、水疱或皲裂，记录暴露时间和部位有助于寻找线索。面部或口唇明显肿胀、呼吸困难时应立即急诊。",
    ),
    (
        "derm-cellulitis-nhs",
        "皮肤科",
        "National Health Service",
        "Cellulitis",
        "https://www.nhs.uk/conditions/cellulitis/",
        "2025-01-01",
        "Open Government Licence v3.0",
        "蜂窝织炎常表现为局部皮肤红、肿、热、痛，范围可能逐渐扩大并伴发热或乏力。红肿迅速扩散、出现水疱、剧痛、寒战或意识改变时应立即就医。",
    ),
    (
        "derm-ringworm-nhs",
        "皮肤科",
        "National Health Service",
        "Ringworm",
        "https://www.nhs.uk/conditions/ringworm/",
        "2025-01-01",
        "Open Government Licence v3.0",
        "体癣常表现为环形、边缘较清楚且伴瘙痒的皮疹，头皮或甲部感染可能有脱发或甲改变。病变迅速扩展、累及头皮或免疫功能受影响时应及时评估。",
    ),
    (
        "derm-warts-nhs",
        "皮肤科",
        "National Health Service",
        "Warts and verrucas",
        "https://www.nhs.uk/conditions/warts-and-verrucas/",
        "2025-01-01",
        "Open Government Licence v3.0",
        "疣和跖疣通常是粗糙的小型皮肤增生，可在手部、足部或其他部位出现。病灶出血、疼痛、颜色或形状改变，或诊断不确定时应由医生检查。",
    ),
    (
        "derm-shingles-nhs",
        "皮肤科",
        "National Health Service",
        "Shingles",
        "https://www.nhs.uk/conditions/shingles/",
        "2025-01-01",
        "Open Government Licence v3.0",
        "带状疱疹常先出现单侧疼痛、灼热或麻刺，随后出现成簇水疱和皮疹。皮疹累及眼睛或面部、出现视力变化、剧烈头痛或免疫功能受损时应尽快就医。",
    ),
    (
        "derm-skin-cancer-nhs",
        "皮肤科",
        "National Health Service",
        "Melanoma skin cancer",
        "https://www.nhs.uk/conditions/melanoma-skin-cancer/",
        "2025-01-01",
        "Open Government Licence v3.0",
        "皮肤癌可能表现为新出现或正在改变的痣、结节或斑块，也可能有反复出血、结痂或久不愈合的皮损。发现持续变化的皮损应尽早由皮肤科检查。",
    ),
    (
        "derm-scabies-nhs",
        "皮肤科",
        "National Health Service",
        "Scabies",
        "https://www.nhs.uk/conditions/scabies/",
        "2025-06-02",
        "Open Government Licence v3.0",
        "疥疮常见夜间剧痒和细小皮疹，家庭成员或密切接触者也可能出现类似症状。皮肤出现厚痂、渗液、明显疼痛或伴发热时应及时就医。",
    ),
    (
        "derm-acne-medlineplus",
        "皮肤科",
        "U.S. National Library of Medicine",
        "Acne",
        "https://medlineplus.gov/acne.html",
        "2025-03-17",
        "U.S. Government work; public domain unless otherwise noted",
        "痤疮可出现粉刺、丘疹、脓疱和结节，严重时可能留下瘢痕。疼痛性深部结节、迅速加重或对自我护理无改善时，应接受皮肤科评估。",
    ),
    (
        "derm-psoriasis-medlineplus",
        "皮肤科",
        "U.S. National Library of Medicine",
        "Psoriasis",
        "https://medlineplus.gov/psoriasis.html",
        "2025-03-17",
        "U.S. Government work; public domain unless otherwise noted",
        "银屑病是可反复发作的炎症性皮肤病，常见红色鳞屑斑块、瘙痒和甲改变，部分人有关节疼痛。皮疹广泛、疼痛明显或伴发热时应及时评估。",
    ),
    (
        "derm-rosacea-medlineplus",
        "皮肤科",
        "U.S. National Library of Medicine",
        "Rosacea",
        "https://medlineplus.gov/rosacea.html",
        "2025-03-17",
        "U.S. Government work; public domain unless otherwise noted",
        "酒渣鼻可表现为面部容易潮红、持续发红、细小血管明显或丘疹脓疱，部分患者有眼部干涩和刺激感。眼痛、畏光或视物模糊时应尽快就医。",
    ),
    (
        "derm-skin-cancer-medlineplus",
        "皮肤科",
        "U.S. National Library of Medicine",
        "Skin Cancer",
        "https://medlineplus.gov/skincancer.html",
        "2025-03-17",
        "U.S. Government work; public domain unless otherwise noted",
        "皮肤癌警示线索包括新出现或发生变化的痣、边界不规则或颜色不均的斑块，以及反复出血或久不愈合的皮损。发现可疑变化应尽早接受皮肤科检查。",
    ),
    (
        "derm-eczema-medlineplus",
        "皮肤科",
        "U.S. National Library of Medicine",
        "Eczema",
        "https://medlineplus.gov/eczema.html",
        "2025-03-17",
        "U.S. Government work; public domain unless otherwise noted",
        "湿疹常有皮肤干燥、瘙痒、红斑、脱屑或渗出，可受刺激因素影响而反复。皮肤明显疼痛、化脓、结痂或伴发热时，应及时评估继发感染。",
    ),
    (
        "derm-hives-medlineplus",
        "皮肤科",
        "U.S. National Library of Medicine",
        "Hives",
        "https://medlineplus.gov/hives.html",
        "2025-03-17",
        "U.S. Government work; public domain unless otherwise noted",
        "荨麻疹表现为突然出现、瘙痒的隆起风团，可在不同部位出现和消退。若伴口唇或舌部肿胀、喉咙紧缩、呼吸困难或头晕，应立即呼叫急救。",
    ),
    (
        "derm-fungal-infections-medlineplus",
        "皮肤科",
        "U.S. National Library of Medicine",
        "Fungal Infections",
        "https://medlineplus.gov/fungalinfections.html",
        "2025-03-17",
        "U.S. Government work; public domain unless otherwise noted",
        "癣是常见的真菌性皮肤感染，可出现环形鳞屑和瘙痒，头皮和甲部感染可能有脱发或甲变色。病变扩大、渗出或累及头皮时应就医确认。",
    ),
    (
        "derm-scabies-medlineplus",
        "皮肤科",
        "U.S. National Library of Medicine",
        "Scabies",
        "https://medlineplus.gov/scabies.html",
        "2025-03-17",
        "U.S. Government work; public domain unless otherwise noted",
        "疥疮常见夜间加重的剧烈瘙痒和丘疹，家庭或密切接触者可能同时出现症状。出现厚痂、皮肤破溃、渗液或明显疼痛时需要皮肤科评估。",
    ),
    (
        "derm-shingles-medlineplus",
        "皮肤科",
        "U.S. National Library of Medicine",
        "Shingles",
        "https://medlineplus.gov/shingles.html",
        "2025-03-17",
        "U.S. Government work; public domain unless otherwise noted",
        "带状疱疹通常表现为单侧疼痛或灼热后出现成簇水疱。皮疹接近眼睛、出现视力异常、面部无力、剧烈头痛或免疫功能受影响时应尽快就医。",
    ),
    (
        "derm-vitiligo-medlineplus",
        "皮肤科",
        "U.S. National Library of Medicine",
        "Vitiligo",
        "https://medlineplus.gov/vitiligo.html",
        "2025-03-17",
        "U.S. Government work; public domain unless otherwise noted",
        "白癜风可出现边界相对清楚的色素脱失斑，分布和进展因人而异。色斑快速扩大、伴眼部或听力异常，或诊断不确定时应接受皮肤科检查。",
    ),
)

# Official page dates were checked against the live source metadata on
# 2026-08-24.  Depending on the publisher, the marker is a publication,
# revision, or last-review date; the API's legacy `published_date` field stores
# that source provenance date.
_SOURCE_PAGE_DATES: dict[str, str] = {
    "card-rheumatic-heart-disease": "2025-01-24",
    "card-salt-reduction": "2026-05-11",
    "card-physical-activity": "2024-06-26",
    "card-healthy-diet": "2026-01-26",
    "card-tobacco": "2026-06-26",
    "card-alcohol": "2024-06-28",
    "card-diabetes": "2024-11-14",
    "card-obesity-overweight": "2025-12-08",
    "card-chagas-disease": "2020-02-04",
    "card-coronary-heart-disease": "2024-12-27",
    "card-heart-attack-nhlbi": "2022-03-24",
    "card-heart-failure-nhlbi": "2022-03-24",
    "card-arrhythmias-nhlbi": "2022-03-24",
    "card-peripheral-artery-disease": "2022-03-24",
    "card-high-blood-pressure-nhlbi": "2024-04-25",
    "card-angina-medlineplus": "2025-03-17",
    "card-heart-valve-diseases-medlineplus": "2025-03-06",
    "card-heart-attack-medlineplus": "2026-01-24",
    "card-heart-failure-medlineplus": "2025-03-11",
    "card-high-blood-pressure-medlineplus": "2026-01-22",
    "card-cholesterol-medlineplus": "2025-03-18",
    "card-stroke-medlineplus": "2025-07-28",
    "card-peripheral-artery-medlineplus": "2025-09-23",
    "card-palpitations-nhs": "2026-06-12",
    "card-heart-attack-nhs": "2026-08-07",
    "resp-tuberculosis-who": "2026-03-24",
    "resp-pneumonia-nhlbi": "2022-03-24",
    "resp-influenza-seasonal-who": "2025-02-28",
    "resp-covid19-who": "2025-11-27",
    "resp-household-air-pollution": "2025-12-16",
    "resp-ambient-air-pollution": "2024-10-24",
    "resp-asthma-nhlbi": "2024-04-17",
    "resp-copd-nhlbi": "2024-11-08",
    "resp-sleep-apnea-nhlbi": "2025-01-09",
    "resp-pulmonary-hypertension-nhlbi": "2023-05-01",
    "resp-pulmonary-embolism-nhlbi": "2022-09-19",
    "resp-bronchitis-medlineplus": "2024-01-26",
    "resp-pneumonia-medlineplus": "2023-12-08",
    "resp-asthma-medlineplus": "2024-01-24",
    "resp-copd-medlineplus": "2026-01-24",
    "resp-rsv-medlineplus": "2025-05-05",
    "resp-tuberculosis-medlineplus": "2024-08-26",
    "resp-flu-medlineplus": "2024-02-28",
    "resp-sleep-apnea-medlineplus": "2025-09-28",
    "resp-cough-nhs": "2026-07-23",
    "resp-shortness-of-breath-nhs": "2026-07-02",
    "resp-asthma-nhs": "2025-04-10",
    "resp-copd-nhs": "2025-07-04",
    "resp-pneumonia-nhs": "2026-07-22",
    "resp-bronchitis-nhs": "2026-08-18",
    "gast-constipation-niddk": "2026-03-18",
    "gast-ibs-niddk": "2017-11-09",
    "gast-crohns-niddk": "2024-07-01",
    "gast-ulcerative-colitis-niddk": "2020-09-16",
    "gast-celiac-niddk": "2025-10-03",
    "gast-lactose-intolerance-niddk": "2026-05-07",
    "gast-gallstones-niddk": "2025-10-03",
    "gast-hemorrhoids-niddk": "2025-10-06",
    "gast-peptic-ulcer-medlineplus": "2024-01-25",
    "gast-viral-gastroenteritis-niddk": "2025-10-06",
    "gast-diverticular-niddk": "2025-10-03",
    "gast-nafld-niddk": "2021-04-01",
    "gast-pancreatitis-niddk": "2025-10-06",
    "gast-gi-bleeding-niddk": "2024-07-01",
    "gast-food-safety-who": "2026-06-04",
    "gast-ibs-medlineplus": "2025-11-18",
    "gast-constipation-medlineplus": "2025-07-21",
    "gast-gallstones-medlineplus": "2025-09-03",
    "gast-pancreatitis-medlineplus": "2024-09-13",
    "gast-celiac-medlineplus": "2026-08-10",
    "gast-crohns-medlineplus": "2023-10-18",
    "gast-ulcerative-colitis-medlineplus": "2024-11-14",
    "gast-hepatitis-medlineplus": "2023-10-20",
    "gast-hemorrhoids-medlineplus": "2023-11-13",
    "gast-gi-bleeding-medlineplus": "2024-11-13",
    "derm-scabies-who": "2023-05-31",
    "derm-psoriasis-niams": "2025-06-05",
    "derm-leprosy-who": "2026-01-23",
    "derm-mycetoma-who": "2022-01-14",
    "derm-lymphatic-filariasis-who": "2024-11-21",
    "derm-acne-nhs": "2024-02-08",
    "derm-psoriasis-nhs": "2026-08-17",
    "derm-rosacea-nhs": "2025-06-02",
    "derm-contact-dermatitis-nhs": "2025-06-25",
    "derm-cellulitis-nhs": "2026-05-12",
    "derm-ringworm-nhs": "2025-06-02",
    "derm-warts-nhs": "2025-07-21",
    "derm-shingles-nhs": "2026-07-07",
    "derm-skin-cancer-nhs": "2026-07-31",
    "derm-scabies-nhs": "2025-06-02",
    "derm-acne-medlineplus": "2024-10-12",
    "derm-psoriasis-medlineplus": "2019-02-20",
    "derm-rosacea-medlineplus": "2024-01-06",
    "derm-skin-cancer-medlineplus": "2025-08-09",
    "derm-eczema-medlineplus": "2025-06-15",
    "derm-hives-medlineplus": "2025-08-06",
    "derm-fungal-infections-medlineplus": "2025-09-21",
    "derm-scabies-medlineplus": "2025-01-07",
    "derm-shingles-medlineplus": "2024-04-20",
    "derm-vitiligo-medlineplus": "2025-12-03",
}


def _doc(row: tuple[str, str, str, str, str, str, str, str]) -> dict[str, str]:
    doc_id, department, institution, title, url, published_date, license, text = row
    published_date = _SOURCE_PAGE_DATES[doc_id]
    return {
        "doc_id": doc_id,
        "department": department,
        "source": f"{institution} | {title}",
        "institution": institution,
        "title": title,
        "url": url,
        "published_date": published_date,
        "version": f"source-{published_date}/medpilot-2026-08-24",
        "license": license,
        "review_status": "approved",
        "text": text,
    }


ADDITIONAL_CORPUS: tuple[dict[str, str], ...] = tuple(_doc(row) for row in _ROWS)
